### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by binarykitchen** [groundwater/node-stackup#8]
My error log has grown huge, 4.5 MB because of this one bug:

```
/var/www/videomail/production/source/node_modules/stackup/trace.js:13
  if (this.stack)  out.push(this.__format(this.stack.stack));
                                                    ^
RangeError: Maximum call stack size exceeded
    at join (native)
    at Trace.toString (/var/www/videomail/production/source/node_modules/stackup/trace.js:13:53)
    at Trace.toString (/var/www/videomail/production/source/node_modules/stackup/trace.js:14:41)
    at Trace.toString (/var/www/videomail/production/source/node_modules/stackup/trace.js:14:41)
    at Trace.toString (/var/www/videomail/production/source/node_modules/stackup/trace.js:14:41)
    at Trace.toString (/var/www/videomail/production/source/node_modules/stackup/trace.js:14:41)
    at Trace.toString (/var/www/videomail/production/source/node_modules/stackup/trace.js:14:41)
    at Trace.toString (/var/www/videomail/production/source/node_modules/stackup/trace.js:14:41)
    at Trace.toString (/var/www/videomail/production/source/node_modules/stackup/trace.js:14:41)
    at Trace.toString (/var/www/videomail/production/source/node_modules/stackup/trace.js:14:41)
    at Trace.toString (/var/www/videomail/production/source/node_modules/stackup/trace.js:14:41)
    at Trace.toString (/var/www/videomail/production/source/node_modules/stackup/trace.js:14:41)
    at Trace.toString (/var/www/videomail/production/source/node_modules/stackup/trace.js:14:41)
   ... and then thousand more lines like these ...
```

Can you add a recursion protection here?

**Comment by defunctzombie** [comment]
Fixed in master?

**Comment by binarykitchen** [comment]
has this been fixed and npm-published yet?
