### ISSUE TITLE
Error: Cannot find module 'shimmer'

### ISSUE THREAD

**Issue by binarykitchen** [groundwater/node-stackup#9]
```
Error: Cannot find module 'shimmer'
    at Function.Module._resolveFilename (module.js:332:15)
    at Function.Module._load (module.js:282:25)
    at Module.require (module.js:361:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/var/www/videomail/production/source/node_modules/stackup/node_modules/async-listener/index.js:5:20)
    at Module._compile (module.js:426:26)
    at Object.Module._extensions..js (module.js:444:10)
    at Module.load (module.js:351:32)
    at Function.Module._load (module.js:306:12)
    at Module.require (module.js:361:17)
module.js:334
    throw err;
```

Solution: bump the async-listener package which fixes the above.

**Comment by binarykitchen** [comment]
hello??

**Comment by binarykitchen** [comment]
has this been fixed and npm-published yet?

**Comment by defunctzombie** [comment]
I pull down master last night and did npm-install and saw that shimmer was installed so I believe this is fixed

**Comment by binarykitchen** [comment]
or right, my bad. all good now, thx
